// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250623115643_NewMigration")]
    partial class NewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9028b685-33c9-4a22-b008-6f2ded3434da"),
                            Author = "Author- 1",
                            CategoryId = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            Title = "title - 1"
                        },
                        new
                        {
                            Id = new Guid("6fa2ee0f-f3e2-49e7-a83f-f980ed6d0ce0"),
                            Author = "Author- 2",
                            CategoryId = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a"),
                            Title = "title - 2"
                        },
                        new
                        {
                            Id = new Guid("19d76285-08df-4bc1-98bf-266b730cea1f"),
                            Author = "Author- 3",
                            CategoryId = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            Title = "title - 3"
                        },
                        new
                        {
                            Id = new Guid("6e28194f-3354-4024-9e97-ea29641b92b3"),
                            Author = "Author- 4",
                            CategoryId = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            Title = "title - 4"
                        },
                        new
                        {
                            Id = new Guid("f41e7c5e-120c-4cbf-b81f-ebdc303aa41e"),
                            Author = "Author- 5",
                            CategoryId = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            Title = "title - 5"
                        },
                        new
                        {
                            Id = new Guid("dd596d44-eeb0-48e2-8d51-21814e453e88"),
                            Author = "Author- 6",
                            CategoryId = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            Title = "title - 6"
                        },
                        new
                        {
                            Id = new Guid("9787fd26-7268-4ff2-80db-83a8bed73dbd"),
                            Author = "Author- 7",
                            CategoryId = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            Title = "title - 7"
                        },
                        new
                        {
                            Id = new Guid("7219c927-5396-4aaf-99a9-945c068ab6bb"),
                            Author = "Author- 8",
                            CategoryId = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a"),
                            Title = "title - 8"
                        },
                        new
                        {
                            Id = new Guid("ba244aab-4906-4c23-ba23-1bd793f2eaf2"),
                            Author = "Author- 9",
                            CategoryId = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a"),
                            Title = "title - 9"
                        },
                        new
                        {
                            Id = new Guid("5719c352-00af-43a9-a9c7-67a3ed9aa2e7"),
                            Author = "Author- 10",
                            CategoryId = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            Title = "title - 10"
                        },
                        new
                        {
                            Id = new Guid("334b2729-702d-4721-a984-60e8f2c61a3d"),
                            Author = "Author- 11",
                            CategoryId = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            Title = "title - 11"
                        },
                        new
                        {
                            Id = new Guid("b01bffa4-093a-44ca-9b10-60f47f3ae2c2"),
                            Author = "Author- 12",
                            CategoryId = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a"),
                            Title = "title - 12"
                        },
                        new
                        {
                            Id = new Guid("b88e6610-64f4-434e-8ee5-a2a9d7e3a511"),
                            Author = "Author- 13",
                            CategoryId = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            Title = "title - 13"
                        },
                        new
                        {
                            Id = new Guid("b17832c9-6cbd-483e-b83c-04c269c42cb1"),
                            Author = "Author- 14",
                            CategoryId = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            Title = "title - 14"
                        },
                        new
                        {
                            Id = new Guid("3d59a3b4-73d4-43e5-b545-6761a12017a1"),
                            Author = "Author- 15",
                            CategoryId = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            Title = "title - 15"
                        },
                        new
                        {
                            Id = new Guid("cdc3fb58-7482-4c95-896d-286774a99a23"),
                            Author = "Author- 16",
                            CategoryId = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            Title = "title - 16"
                        },
                        new
                        {
                            Id = new Guid("bf9822df-3461-4f33-85ca-8289b886acf0"),
                            Author = "Author- 17",
                            CategoryId = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            Title = "title - 17"
                        },
                        new
                        {
                            Id = new Guid("6bc7696e-289c-4bfb-8025-6d3addb93bb0"),
                            Author = "Author- 18",
                            CategoryId = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            Title = "title - 18"
                        },
                        new
                        {
                            Id = new Guid("b182db71-c172-4e6d-bf3a-327d23ddeb14"),
                            Author = "Author- 19",
                            CategoryId = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            Title = "title - 19"
                        },
                        new
                        {
                            Id = new Guid("ff76db7c-0b0a-497a-8229-49f263ec8e33"),
                            Author = "Author- 20",
                            CategoryId = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a"),
                            Title = "title - 20"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            Name = "Sam Raiden"
                        },
                        new
                        {
                            Id = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a"),
                            Name = "Jana McLeaf"
                        },
                        new
                        {
                            Id = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            Name = "Kane Miller"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Blog", b =>
                {
                    b.HasOne("WebApplication1.Models.Category", "Category")
                        .WithMany("Blogs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApplication1.Models.Category", b =>
                {
                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
